askmf/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import index, add_todo

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_todo', add_todo, name='add_todo'),
]

munfess/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import askmf.urls as askmf

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^askmf/', include(askmf,namespace='askmf')),
    url(r'^$', RedirectView.as_view(permanent=True,   url='/askmf/'), name='index')
]

askmf/models.py
from django.db import models

class Todo(models.Model):
    untuk = models.TextField(default='')
    dari = models.TextField(default='')
    description = models.TextField(default='')
    created_date = models.DateTimeField(auto_now_add=True)

askmf/forms.py
from django import forms

class Todo_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    untuk_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 1,
        'class': 'todo-form-input',
        'placeholder':'Tujuan'
    }
    dari_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 1,
        'class': 'todo-form-input',
        'placeholder':'Inisial kamu'
    }
    description_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'todo-form-textarea',
        'placeholder':'Masukan pesanmu'
    }

    untuk = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=untuk_attrs))
    dari = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=dari_attrs))
    description = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))

askmf/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Todo_Form
from .models import Todo

# Create your views here.
response = {}
def index(request):
    response['author'] = "Hilya Auli Fesmia" #TODO Implement yourname
    todo = Todo.objects.all()
    response['todo'] = todo
    html = 'lab_5/lab_5.html'
    response['todo_form'] = Todo_Form
    return render(request, html, response)

def add_todo(request):
    form = Todo_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['untuk'] = request.POST['untuk']
        response['dari'] = request.POST['dari']
        response['description'] = request.POST['description']
        todo = Todo(untuk=response['untuk'],dari=response['dari'],description=response['description'])
        todo.save()
        return HttpResponseRedirect('/askmf/')
    else:
        return HttpResponseRedirect('/askmf/')

askmf/templates/lab_5/lab_5.html
{% extends "lab_5/layout/base.html" %}

{% block content %}
<div name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">munfess 2.0</h2>
        <div class="flex-item col-sm-4">
          <section name="input-list" id="input-list" class="remove-all-margin">
              <div class="container remove-all-margin p-0 ">
                  <form id="form" method="POST" action="{% url 'askmf:add_todo' %}">
                      <h2>Input Todo</h2>
                      {% csrf_token %}
                      {{ todo_form }}
                      <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
                      <br>
                  </form>
              </div>
          </section>
      </div>
        <div class="flex row col-sm-8">
            {% if todo %}
                {% for data in todo reversed %}
                    <div class="flex-item">
                        <div class="to-do-list">
                            <div class="to-do-list-title">
                                untuk : {{data.untuk}}
                            </div>
                            <div class="to-do-list-title">
                                dari : {{data.dari}}
                            </div>
                            <div class="to-do-list-description">
                                {{data.description}}
                            </div>
                            <div class="to-do-list-date-added">
                                {{data.created_date}}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data Todo.
            </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

askmf/templates/lab_5/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 5">
    <meta name="author" content="{{author}}">

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lab_5.css' %}" />

    <!-- bootstrap csss -->

    <title>
        {% block title %} munfess confession {% endblock %}
    </title>
</head>
<body>
    <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
    </content>

    <!-- Jquery n Bootstrap Script -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="application/javascript">
      $(function() {
          $('a[href*="#"]:not([href="#"])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html, body').animate({
                  scrollTop: target.offset().top - 55
                }, 1000);
                return false;
              }
            }
          });
        });
    </script>
</body>
</html>